name: Test user service
on: [push]
jobs:
  start_test_user_service:
    name: test user service
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: test-user
    #     shell:  bash
    steps:
    - run:  ls
